service: rise-hammocks
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev 
  region: us-west-2

plugins:
  - serverless-offline
  - serverless-appsync-plugin

custom: 
  siteName: risehammocks.com
  appSync: 
    - ${file(serverless.appsync-api.yml)}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

resources: 
  Resources: 
    ProfileTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: profileId
            AttributeType: S
        KeySchema:
          - AttributeName: profileId
            KeyType: HASH



