service: rise-hammocks
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev 
  region: us-west-2

plugins: 
  -
custom: 
  siteName: risehammocks.com

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
