service: rise-hammocks
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev 
  region: us-west-2

plugins:
  - serverless-offline
  - serverless-appsync-plugin

custom: 
  siteName: risehammocks.com
  appSync: 
    - ${file(serverless.appsync-api.yml)}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

resources: 
  Resources: 
    CognitoUserPool: 
      Type: AWS::Cognito::UserPool
      Properties:
        MfaConfiguration: OFF 
        UserPoolName: user-pool
        UsernameAttributes:
          - email
        Policies: 
          PasswordPolicy: 
            MinimumLength: 8
            RequireLowercase: False
            RequireNumbers: False
            RequireSymbols: False 
            RequireUppercase: False 

    CognitoUserPoolClient: 
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: user-pool-client
        GenerateSecret: False
        UserPoolId: !Ref CognitoUserPool

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH



