service: rise-hammocks
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev 
  region: us-west-2

plugins:
  - serverless-offline

custom: 
  siteName: risehammocks.com

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

resources: 
  Resources: 
    ProfileTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: email
            AttibuteType: S
        KeySchema: 
          - AttributeName: email
            KeyType: HASH 



